env:
  global:
    - PROJECT_NAME=mike-test
script:
  - true
notifications:
  email: false
language: node_js
node_js:
  - "6"
before_deploy:
  - 'git config --global user.email "deploy@travis-ci"'
  - 'git config --global user.name "[Deploy]"'
  - export GIT_FTP_URL_BRANCH=GIT_FTP_URL_$TRAVIS_BRANCH
  - './git-ftp add-scope $TRAVIS_BRANCH "${!GIT_FTP_URL_BRANCH}"'
  - git config git-ftp.syncroot public
  - npm install -g uglify-js
  - gem install sass-3.4.23.gem --no-ri --no-rdoc
  - gem install dpl-1.8.32.gem --no-ri --no-rdoc
  # - ./git-ftp catchup -s $TRAVIS_BRANCH -v
  - 'FTP_URL="${!GIT_FTP_URL_BRANCH}" ./koi build -e local'
  # - git commit -m deploy --all
deploy:
  - provider: script
    script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
    skip_cleanup: true
    on:
      branch: beta
